(()=>{
  if(document.getElementById('ctdNewsUpdates'))return;
  const anchor=document.querySelector('header.topbar');if(!anchor)return;
  const section=document.createElement('section');section.id='ctdNewsUpdates';section.setAttribute('aria-labelledby','ctdNewsTitle');
  section.innerHTML='<div class="impact-top"><div><span class="impact-kicker">THE DUKE / FIELD NOTES</span><h2 id="ctdNewsTitle">Fantasy impact<span> & takeaways.</span></h2></div><button class="impact-toggle" aria-expanded="true" aria-controls="ctdImpactBody">Collapse −</button></div><div id="ctdImpactBody"><div class="impact-toolbar"><div class="impact-filters" role="group" aria-label="Filter fantasy updates"><button data-filter="all" aria-pressed="true">Top stories</button><button data-filter="availability" aria-pressed="false">Injuries & roles</button><button data-filter="games" aria-pressed="false">Game takeaways</button></div><span class="impact-status" role="status">Loading reports…</span></div><div class="impact-grid"></div><div class="impact-footer"><span>WHAT CHANGED. WHY IT MATTERS. WHAT’S NEXT.</span><button class="impact-more" hidden>More stories ↓</button></div></div>';
  anchor.after(section);
  const style=document.createElement('style');style.textContent=`
#ctdNewsUpdates{--gold:#f4c56a;--muted:#a5afc2;margin:20px 24px 26px;border:1px solid #364052;border-radius:14px;background:#101722;color:#f7f6f0;overflow:hidden;box-shadow:0 12px 32px #0003;font-family:inherit}
#ctdNewsUpdates *{box-sizing:border-box}#ctdNewsUpdates .impact-top{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:20px 24px 17px;border-top:3px solid var(--gold);background:linear-gradient(105deg,#273344 0%,#111925 72%)}
#ctdNewsUpdates .impact-kicker{font-size:10px;font-weight:800;letter-spacing:2.6px;color:var(--gold)}#ctdNewsUpdates h2{font-size:clamp(22px,2.3vw,32px);font-weight:850;letter-spacing:-1px;margin:7px 0 0;line-height:1.1}#ctdNewsUpdates h2 span{color:#b1bdd0;font-weight:500}
#ctdNewsUpdates button{font:inherit;cursor:pointer}#ctdNewsUpdates .impact-toggle{background:transparent;border:1px solid #596276;border-radius:6px;color:#cdd5e2;padding:7px 10px;font-size:11px;white-space:nowrap}#ctdNewsUpdates .impact-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;padding:14px 24px}#ctdNewsUpdates .impact-filters{display:flex;gap:6px;flex-wrap:wrap}#ctdNewsUpdates .impact-filters button{background:transparent;color:#aebbd0;border:1px solid #354055;border-radius:5px;padding:7px 11px;font-size:11px;font-weight:700}#ctdNewsUpdates .impact-filters button[aria-pressed=true]{background:var(--gold);color:#171b23;border-color:var(--gold)}#ctdNewsUpdates .impact-status{color:var(--muted);font-size:11px}
#ctdNewsUpdates .impact-grid{display:grid;grid-template-columns:1.35fr 1fr;gap:12px;padding:0 24px 16px}#ctdNewsUpdates article{--accent:#f4c56a;background:#182130;border:1px solid #344054;border-radius:9px;padding:17px;position:relative;overflow:hidden}#ctdNewsUpdates article:first-child{grid-row:span 2;padding:23px;background:radial-gradient(ellipse at 100% 0%,#55492b55,transparent 70%),#192230;border-left:3px solid var(--accent)}#ctdNewsUpdates article[data-kind="AVAILABILITY"],#ctdNewsUpdates article[data-kind="INJURY WATCH"]{--accent:#ff9b91}#ctdNewsUpdates article[data-kind="BREAKOUT"]{--accent:#71e3b3}#ctdNewsUpdates article[data-kind="UPSET"]{--accent:#c9a2ff}#ctdNewsUpdates article[data-kind="DISAPPOINTMENT"]{--accent:#9bb8fc}
#ctdNewsUpdates article:not(:first-child){padding:12px 15px}#ctdNewsUpdates article:not(:first-child) h3{font-size:16px;margin:8px 0}#ctdNewsUpdates article:not(:first-child) .impact-angle{display:none}#ctdNewsUpdates .impact-label{font-size:10px;font-weight:850;letter-spacing:1.6px;color:var(--accent);display:flex;align-items:center;gap:7px}#ctdNewsUpdates .impact-label:before{content:'';width:6px;height:6px;background:var(--accent);border-radius:1px}#ctdNewsUpdates h3{margin:10px 0;font-size:18px;line-height:1.24;letter-spacing:-.3px}#ctdNewsUpdates article:first-child h3{font-size:clamp(23px,2.3vw,31px);line-height:1.14;max-width:650px}#ctdNewsUpdates a{color:inherit;text-decoration:none}#ctdNewsUpdates a:hover{text-decoration:underline;text-decoration-color:var(--accent)}#ctdNewsUpdates .impact-angle{font-size:12px;line-height:1.6;color:#bac6d8;margin:12px 0 0}#ctdNewsUpdates .impact-angle b{color:var(--accent);font-size:9px;letter-spacing:1.2px;display:block;margin-bottom:4px}#ctdNewsUpdates .impact-meta{font-size:10px;color:#8e9db3;margin:13px 0 0}#ctdNewsUpdates details{margin-top:12px;font-size:12px;color:#bdc8d7;line-height:1.5}#ctdNewsUpdates summary{cursor:pointer;color:#dce4f1;font-size:11px}#ctdNewsUpdates .impact-footer{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 24px;border-top:1px solid #303b4b;color:#8595ae;font-size:9px;font-weight:700;letter-spacing:1.5px}#ctdNewsUpdates .impact-more{color:var(--gold);border:0;background:transparent;font-size:11px;font-weight:700;white-space:nowrap}#ctdNewsUpdates a:focus-visible,#ctdNewsUpdates button:focus-visible,#ctdNewsUpdates summary:focus-visible{outline:2px solid var(--gold);outline-offset:4px}#ctdNewsUpdates [hidden]{display:none!important}#ctdNewsUpdates .impact-empty{padding:18px;color:#aebbd0;font-size:13px;grid-column:1/-1}
@media(max-width:700px){#ctdNewsUpdates{margin:12px 10px 18px}#ctdNewsUpdates .impact-top{padding:16px}#ctdNewsUpdates h2 span{display:block;margin-top:3px}#ctdNewsUpdates .impact-toolbar{padding:12px 16px}#ctdNewsUpdates .impact-grid{grid-template-columns:1fr;padding:0 12px 12px}#ctdNewsUpdates article:first-child{grid-row:auto;padding:18px}#ctdNewsUpdates .impact-footer{padding:12px 16px}#ctdNewsUpdates .impact-footer>span{font-size:8px;letter-spacing:1px}}
`;document.head.append(style);
  let feed=null,expanded=false,busy=false,filter='all';
  const status=section.querySelector('.impact-status'),list=section.querySelector('.impact-grid'),more=section.querySelector('.impact-more');
  const date=value=>Number.isFinite(Date.parse(value))?new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Time unavailable';
  function render(){
    list.replaceChildren();const items=(feed.items||[]).filter(x=>filter==='all'||(filter==='availability'?['AVAILABILITY','INJURY WATCH','ROLE CHANGE'].includes(x.category):!['AVAILABILITY','INJURY WATCH','ROLE CHANGE'].includes(x.category)));
    status.textContent=(feed.status==='CURRENT'?'Feed reviewed ':'Older feed · Reviewed ')+date(feed.reviewed_at);
    if(!items.length){const p=document.createElement('p');p.className='impact-empty';p.textContent='No recent qualifying stories in this view. New verified updates will appear here.';list.append(p)}
    for(const item of items.slice(0,expanded?20:3)){
      let url;try{url=new URL(item.url);if(url.protocol!=='https:')continue}catch{continue}
      const card=document.createElement('article');card.dataset.kind=item.category||'GAME TAKEAWAY';
      const label=document.createElement('div');label.className='impact-label';label.textContent=item.category||'GAME TAKEAWAY';
      const heading=document.createElement('h3'),link=document.createElement('a');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';link.textContent=item.title;heading.append(link);
      const angle=document.createElement('p');angle.className='impact-angle';const eyebrow=document.createElement('b');eyebrow.textContent='WHAT TO WATCH';angle.append(eyebrow,document.createTextNode(item.angle||'Follow the next update for more context.'));
      const meta=document.createElement('p');meta.className='impact-meta';meta.textContent=[item.source,date(item.published_at)].join(' · ');card.append(label,heading,angle,meta);
      if(item.summary){const details=document.createElement('details'),summary=document.createElement('summary'),body=document.createElement('p');summary.textContent='Report details';body.textContent=item.summary;details.append(summary,body);card.append(details)}list.append(card);
    }
    more.hidden=items.length<=3;more.textContent=expanded?'Fewer stories ↑':'More stories ↓';
  }
  more.onclick=()=>{expanded=!expanded;render()};
  section.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;expanded=false;section.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));if(feed)render()});
  section.querySelector('.impact-toggle').onclick=e=>{const body=section.querySelector('#ctdImpactBody');body.hidden=!body.hidden;e.currentTarget.setAttribute('aria-expanded',String(!body.hidden));e.currentTarget.textContent=body.hidden?'Expand +':'Collapse −'};
  async function refresh(){if(busy||document.hidden)return;busy=true;try{const r=await fetch('/api/live/news',{cache:'no-store'});const data=await r.json();if(!r.ok||!Array.isArray(data.items))throw Error('News unavailable');feed=data;render()}catch{if(feed){feed={...feed,status:'STALE'};render();status.textContent+=' · Refresh unavailable'}else status.textContent='News updates temporarily unavailable'}finally{busy=false}}
  refresh();setInterval(refresh,300000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});
})();
