(()=>{
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function install(){const tabs=document.getElementById('weeklyTabs');if(!tabs?.dataset.ctdPublished||document.getElementById('roleWatchTab'))return;const button=document.createElement('button');button.id='roleWatchTab';button.textContent='ROLE WATCH';tabs.append(button);button.onclick=()=>{tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===button));render();};}
 function render(){const mount=document.getElementById('weeklyCategoryMount');if(!mount)return;const rows=window.CTD_ROLE_WATCH?.()||[];const week=window.CTD_PLAYER_OUTLOOK_2026?.week;
  const heading=document.querySelector('#weeklyPage h2');if(heading&&week)heading.textContent='WEEK '+week+' FANTASY';
  mount.innerHTML=`<div class="panel"><p class="roleEyebrow">WEEK ${esc(week||'—')} · OPPORTUNITY TRACKER</p><h2>Role Watch</h2><p class="copy">Who could get more work—and what needs to happen first.</p><div class="roleGrid">${rows.map(r=>`<article class="roleCard"><p class="roleEyebrow">${esc(r.team)} · ${esc(r.position)} ROOM</p><h3>${esc(r.player)} · ${esc(r.designation)}</h3><p>${esc(r.explanation)}</p><h4>Players to watch</h4>${r.options.map(q=>`<div class="rolePlayer">${window.CTD_PLAYER_PORTRAIT?.(q.name,q.athlete_id,q.position)||''}<div><strong>${esc(q.name)}</strong><p class="copy">${esc(q.reason)}${q.status?' · '+esc(q.status):''}</p></div></div>`).join('')}<p class="copy">Next opponent: ${esc(r.opponent)}</p><p class="copy">${esc(r.options.length>1?'The workload may be shared. ':'')}This is a role watch, not a start recommendation.</p>${r.reported?`<small>Injury report: ${esc(new Date(r.reported).toLocaleString())}</small>`:''}${r.source?` · <a href="${esc(r.source)}" target="_blank" rel="noopener">Roster source</a>`:''}</article>`).join('')}</div>${rows.length?'':'<p class="copy">No current injury-driven role changes are available from the published roster.</p>'}</div>`;
 }
 for(const event of ['ctd:published-data-ready','ctd:player-context-ready'])document.addEventListener(event,()=>{install();if(document.getElementById('roleWatchTab')?.classList.contains('active'))render();});install();
 const style=document.createElement('style');style.textContent='.roleGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,340px),1fr));gap:18px;margin-top:24px}.roleCard{background:#102033;border:1px solid #2d4c6b;border-top:3px solid #f3c766;border-radius:12px;padding:22px}.roleCard h3{font-size:22px;margin:8px 0 14px}.roleCard h4{font-size:14px;color:#f3c766;margin:22px 0 12px}.roleCard p{line-height:1.65;font-size:14px}.roleEyebrow{font-size:11px!important;letter-spacing:.14em;color:#91bfff}.rolePlayer{display:flex;align-items:center;gap:12px;margin:14px 0}.rolePlayer p{margin:4px 0}.roleCard small,.roleCard a{font-size:11px;color:#a9bdd5}';document.head.append(style);
})();
