const SCOREBOARD='https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard';
const SUMMARY='https://site.api.espn.com/apis/site/v2/sports/football/nfl/summary';
const RAW='https://raw.githubusercontent.com/brandonlowery013-glitch/-fantasy-2026-player-comparison-/frontend/ctd-cloudflare-work';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'};
const now=()=>new Date().toISOString();
async function getJson(url,cf){const r=await fetch(url,{headers:{accept:'application/json'},cf});if(!r.ok)throw Error(`${r.status} ${url}`);return r.json()}
function scores(j){return(j.events||[]).map(e=>{const c=e.competitions?.[0]||{},cs=c.competitors||[],a=cs.find(x=>x.homeAway==='away'),h=cs.find(x=>x.homeAway==='home');return{event_id:String(e.id),start_at:e.date,away:{team:a?.team?.abbreviation,score:Number(a?.score||0),logo:a?.team?.logo||null},home:{team:h?.team?.abbreviation,score:Number(h?.score||0),logo:h?.team?.logo||null},state:e.status?.type?.state||null,status:e.status?.type?.shortDetail||e.status?.type?.detail||'Scheduled',clock:e.status?.displayClock||null,period:e.status?.period||null}})}
function game(j){const c=j.header?.competitions?.[0]||{},cs=c.competitors||[],a=cs.find(x=>x.homeAway==='away'),h=cs.find(x=>x.homeAway==='home'),ps=[];for(const t of j.boxscore?.players||[])for(const g of t.statistics||[])for(const x of g.athletes||[])ps.push({team:t.team?.abbreviation,category:g.name||g.displayName,player:x.athlete?.displayName,player_id:x.athlete?.id,stats:Object.fromEntries((g.labels||[]).map((k,i)=>[k,x.stats?.[i]??null]))});const inj=[];for(const t of j.injuries||[])for(const x of t.injuries||[])inj.push({team:t.team?.abbreviation,player:x.athlete?.displayName,player_id:x.athlete?.id,status:x.status||x.details?.type||'UNKNOWN',detail:x.details?.detail||null});return{event_id:String(c.id||''),away:{team:a?.team?.abbreviation,score:Number(a?.score||0)},home:{team:h?.team?.abbreviation,score:Number(h?.score||0)},state:c.status?.type?.state,status:c.status?.type?.shortDetail,clock:c.status?.displayClock,period:c.status?.period,player_stats:ps,injuries:inj,team_stats:(j.boxscore?.teams||[]).map(t=>({team:t.team?.abbreviation,stats:Object.fromEntries((t.statistics||[]).map(s=>[s.name||s.displayName,s.displayValue??s.value]))})),scoring_plays:(j.scoringPlays||[]).map(x=>({period:x.period?.number,clock:x.clock?.displayValue,team:x.team?.abbreviation,text:x.text,away_score:x.awayScore,home_score:x.homeScore})),drives:(j.drives?.previous||[]).slice(-15).reverse().map(d=>({team:d.team?.abbreviation,result:d.result,description:d.description||d.result,plays:d.plays?.length,yards:d.yards,time:d.timeElapsed?.displayValue}))}}
async function raw(path){return getJson(`${RAW}/${path}?v=${Date.now()}`,{cacheTtl:20,cacheEverything:true})}
async function bundle(event){const tasks=[getJson(`${SCOREBOARD}?limit=100&dates=2026&ts=${Date.now()}`,{cacheTtl:8,cacheEverything:true}),raw('data/market/unified-opportunities-2026.json'),raw('data/market/final-betting-ui-feed-2026.json'),raw('data/ingestion/live-injury-poll-2026.json'),raw('data/weekly/weekly-player-outlook-2026.json')];const [s,m,b,i,p]=await Promise.allSettled(tasks);let g=null;if(event){try{g=game(await getJson(`${SUMMARY}?event=${encodeURIComponent(event)}&ts=${Date.now()}`,{cacheTtl:8,cacheEverything:true}))}catch{}}return{generated_at:now(),scoreboard:s.status==='fulfilled'?scores(s.value):[],game:g,model:m.status==='fulfilled'?m.value:null,betting:b.status==='fulfilled'?b.value:null,injuries:i.status==='fulfilled'?i.value:null,player_outlook:p.status==='fulfilled'?p.value:null,sources:{scoreboard:s.status,model:m.status,betting:b.status,injuries:i.status,player_outlook:p.status}}}
const out=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:H});
export async function onRequest(context){if(context.request.method==='OPTIONS')return new Response(null,{headers:{...H,'access-control-allow-methods':'GET,OPTIONS'}});const u=new URL(context.request.url),path=(context.params.path||[]);const leaf=Array.isArray(path)?path.join('/'):String(path||'');try{if(leaf==='health'||leaf==='')return out({status:'READY',generated_at:now(),transport:'Cloudflare Pages Function',cadence_seconds:{scores:8,bundle:15,repo_feeds:20}});if(leaf==='scoreboard')return out({generated_at:now(),games:scores(await getJson(`${SCOREBOARD}?limit=100&dates=2026&ts=${Date.now()}`,{cacheTtl:8,cacheEverything:true}))});if(leaf==='game'){const id=u.searchParams.get('event');if(!id)return out({error:'event required'},400);return out({generated_at:now(),game:game(await getJson(`${SUMMARY}?event=${encodeURIComponent(id)}&ts=${Date.now()}`,{cacheTtl:8,cacheEverything:true}))});}if(leaf==='bundle')return out(await bundle(u.searchParams.get('event')));if(leaf==='model')return out({generated_at:now(),data:await raw('data/market/unified-opportunities-2026.json')});if(leaf==='betting')return out({generated_at:now(),data:await raw('data/market/final-betting-ui-feed-2026.json')});if(leaf==='injuries')return out({generated_at:now(),data:await raw('data/ingestion/live-injury-poll-2026.json')});if(leaf==='players')return out({generated_at:now(),data:await raw('data/weekly/weekly-player-outlook-2026.json')});return out({error:'not found'},404)}catch(e){return out({status:'DEGRADED',generated_at:now(),error:e.message},502)}}
