const CDN_SCOREBOARD='https://cdn.espn.com/core/nfl/scoreboard?xhr=1&limit=50';
const CDN_GAME=id=>`https://cdn.espn.com/core/nfl/game?xhr=1&gameId=${encodeURIComponent(id)}`;
const SITE_SCOREBOARD='https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?limit=100&dates=2026';
const SITE_SUMMARY=id=>`https://site.api.espn.com/apis/site/v2/sports/football/nfl/summary?event=${encodeURIComponent(id)}`;
const RAW='https://raw.githubusercontent.com/brandonlowery013-glitch/-fantasy-2026-player-comparison-/frontend/ctd-cloudflare-work';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'};
const now=()=>new Date().toISOString();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let lastLiveSignature=null,lastLiveChangeAt=0;

async function getJson(url,ttl=0){
  let last;
  for(let attempt=0;attempt<2;attempt++){
    try{
      const r=await fetch(url,{headers:{accept:'application/json','user-agent':'ChuckTheDuke/2026'},cf:ttl?{cacheTtl:ttl,cacheEverything:true}:undefined});
      if(!r.ok){const e=new Error(`${r.status} ${url}`);e.status=r.status;throw e}
      return await r.json();
    }catch(e){last=e;if(attempt===0&&(e.status===429||e.status>=500||!e.status))await sleep(180)}
  }
  throw last;
}
function scoreboardEvents(j){return j?.content?.sbData?.events||j?.events||j?.gamepackageJSON?.events||[]}
function unwrapGame(j){return j?.gamepackageJSON||j?.content?.gamepackageJSON||j?.content?.gamepackage||j||{}}
function scores(j){return scoreboardEvents(j).map(e=>{const c=e.competitions?.[0]||{},cs=c.competitors||[],a=cs.find(x=>x.homeAway==='away'),h=cs.find(x=>x.homeAway==='home'),s=e.status||c.status||{};return{event_id:String(e.id||c.id||''),start_at:e.date||c.date||c.startDate||null,away:{team:a?.team?.abbreviation||a?.team?.shortDisplayName||null,score:Number(a?.score||0),logo:a?.team?.logo||null},home:{team:h?.team?.abbreviation||h?.team?.shortDisplayName||null,score:Number(h?.score||0),logo:h?.team?.logo||null},state:s.type?.state||null,status:s.type?.shortDetail||s.type?.detail||s.type?.description||'Scheduled',clock:s.displayClock||null,period:s.period??null,venue:c.venue?.fullName||null}})}
function validScores(games){return Array.isArray(games)&&games.length>0&&games.every(g=>g.event_id&&g.away?.team&&g.home?.team&&Number.isFinite(g.away.score)&&Number.isFinite(g.home.score))}
function liveLooksStale(games){const live=games.filter(g=>String(g.state||'').toLowerCase()==='in');if(!live.length){lastLiveSignature=null;lastLiveChangeAt=0;return false}const sig=JSON.stringify(live.map(g=>[g.event_id,g.away.score,g.home.score,g.period,g.clock]));const t=Date.now();if(sig!==lastLiveSignature){lastLiveSignature=sig;lastLiveChangeAt=t;return false}return lastLiveChangeAt&&t-lastLiveChangeAt>90000}
async function cacheLastGood(key,value){try{if(!globalThis.caches?.default)return;await caches.default.put(new Request(`https://ctd.internal/${key}`),new Response(JSON.stringify({saved_at:now(),value}),{headers:{'content-type':'application/json','cache-control':'public,max-age=600'}}))}catch{}}
async function readLastGood(key){try{if(!globalThis.caches?.default)return null;const r=await caches.default.match(new Request(`https://ctd.internal/${key}`));return r?await r.json():null}catch{return null}}
async function liveScoreboard(){
  const errors=[];
  try{const raw=await getJson(`${CDN_SCOREBOARD}&ts=${Date.now()}`,5),games=scores(raw);if(!validScores(games))throw Error('CDN scoreboard schema invalid');if(liveLooksStale(games))throw Error('CDN live scoreboard stale >90s');await cacheLastGood('scoreboard',games);return{games,health:{status:'LIVE',provider:'espn-cdn',fallback:false,errors}}}catch(e){errors.push(`espn-cdn: ${e.message}`)}
  try{const raw=await getJson(`${SITE_SCOREBOARD}&ts=${Date.now()}`,5),games=scores(raw);if(!validScores(games))throw Error('Site API scoreboard schema invalid');await cacheLastGood('scoreboard',games);return{games,health:{status:'FALLBACK',provider:'espn-site-api',fallback:true,errors}}}catch(e){errors.push(`espn-site-api: ${e.message}`)}
  const cached=await readLastGood('scoreboard');if(cached?.value&&validScores(cached.value))return{games:cached.value,health:{status:'STALE',provider:'last-known-good',fallback:true,saved_at:cached.saved_at,errors}};
  throw Error(errors.join(' | '));
}
function game(j){const x=unwrapGame(j),c=x.header?.competitions?.[0]||x.competitions?.[0]||{},cs=c.competitors||[],a=cs.find(v=>v.homeAway==='away'),h=cs.find(v=>v.homeAway==='home'),ps=[];for(const t of x.boxscore?.players||[])for(const g of t.statistics||[])for(const p of g.athletes||[])ps.push({team:t.team?.abbreviation||null,category:g.name||g.displayName||null,player:p.athlete?.displayName||null,player_id:p.athlete?.id||null,stats:Object.fromEntries((g.labels||[]).map((k,i)=>[k,p.stats?.[i]??null]))});const inj=[];for(const t of x.injuries||[])for(const p of t.injuries||[])inj.push({team:t.team?.abbreviation||null,player:p.athlete?.displayName||null,player_id:p.athlete?.id||null,status:p.status||p.details?.type||'UNKNOWN',detail:p.details?.detail||null});return{event_id:String(c.id||x.header?.id||x.id||''),away:{team:a?.team?.abbreviation||null,score:Number(a?.score||0)},home:{team:h?.team?.abbreviation||null,score:Number(h?.score||0)},state:c.status?.type?.state||x.header?.status?.type?.state||null,status:c.status?.type?.shortDetail||x.header?.status?.type?.shortDetail||null,clock:c.status?.displayClock||x.header?.status?.displayClock||null,period:c.status?.period??x.header?.status?.period??null,player_stats:ps,injuries:inj,team_stats:(x.boxscore?.teams||[]).map(t=>({team:t.team?.abbreviation,stats:Object.fromEntries((t.statistics||[]).map(s=>[s.name||s.displayName,s.displayValue??s.value]))})),scoring_plays:(x.scoringPlays||[]).map(p=>({period:p.period?.number,clock:p.clock?.displayValue,team:p.team?.abbreviation,text:p.text,away_score:p.awayScore,home_score:p.homeScore})),drives:(x.drives?.previous||x.drives?.current?[...(x.drives?.previous||[]),...(x.drives?.current?[x.drives.current]:[])]:[]).slice(-15).reverse().map(d=>({team:d.team?.abbreviation,result:d.result,description:d.description||d.result,plays:d.plays?.length,yards:d.yards,time:d.timeElapsed?.displayValue})),plays:(x.plays||[]).slice(-40).reverse().map(p=>({period:p.period?.number,clock:p.clock?.displayValue,text:p.text,type:p.type?.text}))}}
function validGame(g,id){return g&&String(g.event_id||id)===String(id)&&g.away?.team&&g.home?.team}
async function liveGame(id){const errors=[];try{const g=game(await getJson(`${CDN_GAME(id)}&ts=${Date.now()}`,5));if(!validGame(g,id))throw Error('CDN game schema invalid');await cacheLastGood(`game-${id}`,g);return{game:g,health:{status:'LIVE',provider:'espn-cdn',fallback:false,errors}}}catch(e){errors.push(`espn-cdn: ${e.message}`)}try{const g=game(await getJson(`${SITE_SUMMARY(id)}&ts=${Date.now()}`,5));if(!validGame(g,id))throw Error('Site summary schema invalid');await cacheLastGood(`game-${id}`,g);return{game:g,health:{status:'FALLBACK',provider:'espn-site-api',fallback:true,errors}}}catch(e){errors.push(`espn-site-api: ${e.message}`)}const cached=await readLastGood(`game-${id}`);if(cached?.value)return{game:cached.value,health:{status:'STALE',provider:'last-known-good',fallback:true,saved_at:cached.saved_at,errors}};throw Error(errors.join(' | '))}
async function raw(path){return getJson(`${RAW}/${path}?v=${Date.now()}`,20)}
async function bundle(event){const [live,m,b,i,p]=await Promise.all([liveScoreboard(),raw('data/market/unified-opportunities-2026.json').catch(()=>null),raw('data/market/final-betting-ui-feed-2026.json').catch(()=>null),raw('data/ingestion/live-injury-poll-2026.json').catch(()=>null),raw('data/weekly/weekly-player-outlook-2026.json').catch(()=>null)]);let gd=null;if(event)gd=await liveGame(event).catch(e=>({game:null,health:{status:'ERROR',provider:null,fallback:true,errors:[e.message]}}));return{generated_at:now(),scoreboard:live.games,game:gd?.game||null,model:m,betting:b,injuries:i,player_outlook:p,health:{scoreboard:live.health,game:gd?.health||null,model:m?'LIVE':'ERROR',betting:b?'LIVE':'ERROR',injuries:i?'LIVE':'ERROR',player_outlook:p?'LIVE':'ERROR'}}}
const out=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:H});
export async function onRequest(context){if(context.request.method==='OPTIONS')return new Response(null,{headers:{...H,'access-control-allow-methods':'GET,OPTIONS'}});const u=new URL(context.request.url),p=context.params.path||[],leaf=Array.isArray(p)?p.join('/'):String(p||'');try{if(leaf==='health'||leaf===''){const s=await liveScoreboard();return out({status:s.health.status,generated_at:now(),transport:'Cloudflare Pages Function',primary:'espn-cdn',fallback:'espn-site-api',last_known_good:true,cadence_seconds:{scores:5,bundle:15,repo_feeds:20},provider_health:s.health})}if(leaf==='scoreboard'){const s=await liveScoreboard();return out({generated_at:now(),games:s.games,health:s.health})}if(leaf==='game'){const id=u.searchParams.get('event');if(!id)return out({error:'event required'},400);const g=await liveGame(id);return out({generated_at:now(),game:g.game,health:g.health})}if(leaf==='bundle')return out(await bundle(u.searchParams.get('event')));if(leaf==='model')return out({generated_at:now(),data:await raw('data/market/unified-opportunities-2026.json')});if(leaf==='betting')return out({generated_at:now(),data:await raw('data/market/final-betting-ui-feed-2026.json')});if(leaf==='injuries')return out({generated_at:now(),data:await raw('data/ingestion/live-injury-poll-2026.json')});if(leaf==='players')return out({generated_at:now(),data:await raw('data/weekly/weekly-player-outlook-2026.json')});return out({error:'not found'},404)}catch(e){return out({status:'DEGRADED',generated_at:now(),error:e.message},502)}}
