from pathlib import Path
p=Path('index.html')
s=p.read_text()
if 'function marketGap(' not in s:
    s=s.replace("function rankGap(a,b){return a==null||b==null?null:Math.round(Math.abs(a-b))}","function rankGap(a,b){return a==null||b==null?null:Math.round(Math.abs(a-b))}\nfunction marketGap(p){if(p.ad==null||p.o==null)return '—';let g=Math.round(p.ad-p.o);return `${g>0?'+':''}${g}`}\nfunction priceRead(p){return p.px==='BUY'?'VALUE':p.px||'—'}")
s=s.replace("function truePanel(p){return blocks([['Our Draft Rank',`#${p.o}`],['True Value Rank',`#${p.tr}`],['Consensus Rank',p.cr==null?'—':`#${p.cr}`],['Market ADP',fmt(p.ad)]])+readBlock('What it means',marketRead(p))}","function truePanel(p){return blocks([['Our Rank',`#${p.o}`],['Consensus Rank',p.cr==null?'—':`#${p.cr}`],['Market ADP',fmt(p.ad)],['Vs Market',marketGap(p)],['True Value Rank',`#${p.tr}`]])}")
s=s.replace("function valuePanel(p){return blocks([['Our Draft Rank',`#${p.o}`],['Consensus',p.cr==null?'—':`#${p.cr}`],['ADP',fmt(p.ad)],['Fair Draft Range',p.fw||'—'],['Draft Price Verdict',p.px]])+readBlock('Why',marketRead(p))}","function valuePanel(p){return blocks([['Our Rank',`#${p.o}`],['Consensus Rank',p.cr==null?'—':`#${p.cr}`],['Market ADP',fmt(p.ad)],['Vs Market',marketGap(p)],['Price Read',priceRead(p)],['Fair Draft Range',p.fw||'—']])}")
old="function card(p,ps){let rankWin=snapshotWinner(ps,'o',true),tvWin=snapshotWinner(ps,'tr',true),projWin=snapshotWinner(ps,'mp'),consProjWin=snapshotWinner(ps,'cp'),availWin=snapshotWinner(ps,'a');return `<div class=\"pcard\"><h3>${p.n}</h3><div class=\"small\">${p.t} · ${p.p}</div><span class=\"tag ${css(p.px)}\">${p.px}: ${priceMeaning(p)}</span>${snapshotStat('Our Draft Rank',`#${p.o}`,p.n===rankWin)}${snapshotStat('Consensus',p.cr==null?'—':`#${p.cr}`)}${snapshotStat('ADP',fmt(p.ad))}${snapshotStat('True Value Rank',`#${p.tr}`,p.n===tvWin,'Our price-independent player ranking')}${snapshotStat('Our Projected PPR',fmt(p.mp,1),p.n===projWin)}${snapshotStat('Consensus PPR',fmt(p.cp,1),p.n===consProjWin)}${snapshotStat('Availability',publicAvailability(p),p.n===availWin,'Current health / expected availability')}${readBlock('Market read',marketRead(p))}</div>`}"
new="function card(p,ps){let rankWin=snapshotWinner(ps,'o',true),tvWin=snapshotWinner(ps,'tr',true),projWin=snapshotWinner(ps,'mp'),consProjWin=snapshotWinner(ps,'cp'),availWin=snapshotWinner(ps,'a');return `<div class=\"pcard\"><h3>${p.n}</h3><div class=\"small\">${p.t} · ${p.p}</div><span class=\"tag ${css(p.px)}\">${priceRead(p)}</span>${snapshotStat('Our Rank',`#${p.o}`,p.n===rankWin)}${snapshotStat('Consensus Rank',p.cr==null?'—':`#${p.cr}`)}${snapshotStat('Market ADP',fmt(p.ad))}${snapshotStat('Vs Market',marketGap(p))}${snapshotStat('True Value Rank',`#${p.tr}`,p.n===tvWin,'Our price-independent player ranking')}${snapshotStat('Our Projected PPR',fmt(p.mp,1),p.n===projWin)}${snapshotStat('Consensus PPR',fmt(p.cp,1),p.n===consProjWin)}${snapshotStat('Availability',publicAvailability(p),p.n===availWin,'Current health / expected availability')}</div>`}"
s=s.replace(old,new)
s=s.replace('<b>BUY</b><span>Market price is cheaper than our valuation.</span>','<b>VALUE</b><span>Market price is favorable relative to our full current-cost evaluation.</span>')
s=s.replace("Our draft rank, consensus and ADP show where our valuation differs from the market. This section does not decide who is the better player.","Our rank, consensus rank and market ADP are shown separately. Vs Market is simply Market ADP minus Our Rank.")
s=s.replace("This is where our draft rank, consensus and ADP become the price decision.","This is where our rank, consensus rank, market ADP, fair range and full player profile become the price decision.")
p.write_text(s)
